In [ ]:
# Normalización de datos con base en https://www.youtube.com/watch?v=ro2UjY8dLWw

In [16]:
import pandas as pd


df = pd.read_csv("/home/omnibus/Documents/QGISS_Cartografia/Proyectos/criminal_mx/indice_psd/cruce.csv")

In [2]:
display(df)

,CVEGEO,CVE_ENT,CVE_MUN,Estado,Municipios,DCVEGEO,DEstado,DMunicipio,DNOM_MUN,DRRIAlt,...,MDEPORTA,MOTRA,MNO_ESP,Mtasa_mig1,Mtasa_mi_1,Mpobtotal2,Mporcien_I,densidad_o,densidad_1,densidad_2
0,1001,1,1,Aguascalientes,Aguascalientes,NaN,Aguascalientes,Aguascalientes,Aguascalientes,0.099400,...,0,3239,101,4.0,43.0,961977,1.0,NaN,Aguascalientes,2
1,1002,1,2,Aguascalientes,Asientos,NaN,Aguascalientes,Asientos,Asientos,0.407417,...,0,84,6,3.0,39.0,50864,1.0,NaN,Asientos,1
2,1003,1,3,Aguascalientes,Calvillo,NaN,Aguascalientes,Calvillo,Calvillo,0.419558,...,0,60,11,0.0,9.0,60760,0.0,NaN,Calvillo,1
3,1004,1,4,Aguascalientes,Cosío,NaN,Aguascalientes,Cosío,Cosío,0.446193,...,0,44,1,1.0,17.0,16918,0.0,NaN,Cosío,2
4,1005,1,5,Aguascalientes,Jesús María,NaN,Aguascalientes,Jesús María,Jesús María,0.265166,...,0,581,21,7.0,73.0,130184,2.0,NaN,Jesús María,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2460,32054,32,54,Zacatecas,Villa Hidalgo,NaN,Zacatecas,Villa Hidalgo,Villa Hidalgo,0.522400,...,0,34,0,2.0,29.0,20177,0.0,NaN,Villa Hidalgo,1
2461,32055,32,55,Zacatecas,Villanueva,NaN,Zacatecas,Villanueva,Villanueva,0.482641,...,0,48,4,3.0,34.0,31804,1.0,NaN,Villanueva,2
2462,32056,32,56,Zacatecas,Zacatecas,NaN,Zacatecas,Zacatecas,Zacatecas,0.129917,...,0,1774,75,29.0,294.0,155533,2.0,NaN,Zacatecas,1
2463,32057,32,57,Zacatecas,Trancoso,NaN,Zacatecas,Trancoso,Trancoso,0.346497,...,0,39,0,4.0,49.0,20285,2.0,NaN,Trancoso,1
2464,32058,32,58,Zacatecas,Santa María de la Paz,NaN,Zacatecas,Santa María de la Paz,Santa María de la Paz,0.609889,...,0,5,0,0.0,0.0,2855,0.0,NaN,Santa María de la Paz,0

In [3]:
# Describir las variables

In [4]:
df[["Dt_del10mi", "Mtasa_mig1", "densidad_2", "tasa_ata1", "DRRIAlt"]].describe()

        Dt_del10mi   Mtasa_mig1   densidad_2    tasa_ata1      DRRIAlt
count  2457.000000  2465.000000  2465.000000  1557.000000  2456.000000
mean      9.976657     7.801623     0.733063     2.791478     0.438019
std       8.722803    15.984291     0.964120     4.708370     0.147258
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       4.143967     0.000000     0.000000     0.709622     0.354977
50%       7.864737     3.000000     0.000000     1.472066     0.448476
75%      12.687961     8.000000     1.000000     3.137581     0.545929
max      73.197308   250.000000     9.000000    81.148564     0.840911

In [7]:
#Simple feature scaling

df["Dt_del10mi"] = df["Dt_del10mi"]/df["Dt_del10mi"].max()

In [ ]:
#Min-Max
df["Mtasa_mig1"] = df["Mtasa_mig1"]-df["Mtasa_mig1"].min()/df["Mtasa_mig1"].max()-df["Mtasa_mig1"].min()

In [ ]:

df["densidad_2"] = df["densidad_2"]-df["densidad_2"].mean()/df["densidad_2"].std()

In [ ]:
"tasa_ata1"

In [ ]:
"DRRIAlt"

In [15]:
#exportar a .csv
df[["Dt_del10mi", "Mtasa_mig1", "densidad_2", "tasa_ata1", "DRRIAlt"]].describe().to_csv("result_summary.csv", index=False)

NameError: name 'df_result' is not defined

In [1]:
# Nombre del campo para el que deseas calcular la media y la mediana
campo = "nombre_del_campo"

# Calcular la media y la mediana
media = df[campo].mean()
mediana = df[campo].median()

# Mostrar los resultados
print(f"Media de {campo}: {media}")
print(f"Mediana de {campo}: {mediana}")

NameError: name 'df' is not defined

In [10]:
import pandas as pd

# Supongamos que ya tienes tu DataFrame df con las variables
variables = ["Dt_del10mi", "Mtasa_mig1", "densidad_2", "tasa_ata1", "DRRIAlt"]
description = df[variables].describe()

# Calcula la mediana y crea un DataFrame para la fila de la mediana
median_row = pd.DataFrame(df[variables].median(), columns=['median']).transpose()

# Concatena el DataFrame de la mediana con la descripción
description_with_median = pd.concat([description, median_row])

print(description_with_median)

         Dt_del10mi   Mtasa_mig1   densidad_2    tasa_ata1      DRRIAlt
count   2457.000000  2465.000000  2465.000000  1557.000000  2456.000000
mean       9.976657     7.801623     0.733063     2.791478     0.438019
std        8.722803    15.984291     0.964120     4.708370     0.147258
min        0.000000     0.000000     0.000000     0.000000     0.000000
25%        4.143967     0.000000     0.000000     0.709622     0.354977
50%        7.864737     3.000000     0.000000     1.472066     0.448476
75%       12.687961     8.000000     1.000000     3.137581     0.545929
max       73.197308   250.000000     9.000000    81.148564     0.840911
median     7.864737     3.000000     0.000000     1.472066     0.448476

# Transformación logarítmica

In [5]:
import numpy as np
import pandas as pd

#  DataFrame llamado df y las variables del índice en la lista "variables"
variables = ["Dt_del10mi", "Mtasa_mig1", "densidad_2", "tasa_ata1", "DRRIAlt"]

# Recorre la lista de variables y crea nuevos campos logaritmizados
for variable in variables:
    new_field_name = f"l_{variable}"
    df[new_field_name] = np.log(df[variable] + 1)  # Añade 1 para evitar log(0)

# Verifica el DataFrame con los nuevos campos logaritmizados
print(df)

      CVEGEO  CVE_ENT  CVE_MUN          Estado             Municipios  \
0       1001        1        1  Aguascalientes         Aguascalientes
1       1002        1        2  Aguascalientes               Asientos
2       1003        1        3  Aguascalientes               Calvillo
3       1004        1        4  Aguascalientes                  Cosío
4       1005        1        5  Aguascalientes            Jesús María
...      ...      ...      ...             ...                    ...
2460   32054       32       54       Zacatecas          Villa Hidalgo
2461   32055       32       55       Zacatecas             Villanueva
2462   32056       32       56       Zacatecas              Zacatecas
2463   32057       32       57       Zacatecas               Trancoso
2464   32058       32       58       Zacatecas  Santa María de la Paz

      DCVEGEO         DEstado             DMunicipio               DNOM_MUN  \
0         NaN  Aguascalientes         Aguascalientes         Aguascalientes
1         NaN  Aguascalientes               Asientos               Asientos
2         NaN  Aguascalientes               Calvillo               Calvillo
3         NaN  Aguascalientes                  Cosío                  Cosío
4         NaN  Aguascalientes            Jesús María            Jesús María
...       ...             ...                    ...                    ...
2460      NaN       Zacatecas          Villa Hidalgo          Villa Hidalgo
2461      NaN       Zacatecas             Villanueva             Villanueva
2462      NaN       Zacatecas              Zacatecas              Zacatecas
2463      NaN       Zacatecas               Trancoso               Trancoso
2464      NaN       Zacatecas  Santa María de la Paz  Santa María de la Paz

       DRRIAlt  ...  Mpobtotal2  Mporcien_I  densidad_o  \
0     0.099400  ...      961977         1.0         NaN
1     0.407417  ...       50864         1.0         NaN
2     0.419558  ...       60760         0.0         NaN
3     0.446193  ...       16918         0.0         NaN
4     0.265166  ...      130184         2.0         NaN
...        ...  ...         ...         ...         ...
2460  0.522400  ...       20177         0.0         NaN
2461  0.482641  ...       31804         1.0         NaN
2462  0.129917  ...      155533         2.0         NaN
2463  0.346497  ...       20285         2.0         NaN
2464  0.609889  ...        2855         0.0         NaN

                 densidad_1  densidad_2  l_Dt_del10mi  l_Mtasa_mig1  \
0            Aguascalientes           2      3.640439      1.609438
1                  Asientos           1      3.100656      1.386294
2                  Calvillo           1      2.986837      0.000000
3                     Cosío           2      2.844269      0.693147
4               Jesús María           2      3.211325      2.079442
...                     ...         ...           ...           ...
2460          Villa Hidalgo           1      1.719222      1.098612
2461             Villanueva           2      2.672378      1.386294
2462              Zacatecas           1      3.465194      3.401197
2463               Trancoso           1      3.060649      1.609438
2464  Santa María de la Paz           0      2.655779      0.000000

      l_densidad_2  l_tasa_ata1  l_DRRIAlt
0         1.098612     0.272353   0.094764
1         0.693147     0.334943   0.341756
2         0.693147     0.289028   0.350346
3         1.098612     0.643356   0.368935
4         1.098612     0.387738   0.235203
...            ...          ...        ...
2460      0.693147     0.153666   0.420288
2461      1.098612     0.905353   0.393825
2462      0.693147     1.838397   0.122145
2463      0.693147     1.635751   0.297506
2464      0.000000     1.507939   0.476165

[2465 rows x 61 columns]

In [6]:
# Guarda el DataFrame modificado en un nuevo archivo CSV
new_csv_filename = "/home/omnibus/Documents/QGISS_Cartografia/Proyectos/criminal_mx/indice_psd/cruce_trans_log.csv"
df.to_csv(new_csv_filename, index=False)  # El parámetro index=False evita guardar el índice como columna

print(f"DataFrame modificado guardado en {new_csv_filename}")

DataFrame modificado guardado en /home/omnibus/Documents/QGISS_Cartografia/Proyectos/criminal_mx/indice_psd/cruce_trans_log.csv

# Vamos a verificar cómo salió

In [7]:
df[["l_Dt_del10mi", "l_Mtasa_mig1", "l_densidad_2", "l_tasa_ata1", "l_DRRIAlt"]].describe()

       l_Dt_del10mi  l_Mtasa_mig1  l_densidad_2  l_tasa_ata1    l_DRRIAlt
count   2457.000000   2465.000000   2465.000000  1557.000000  2456.000000
mean       2.124137      1.355510      0.426095     1.036280     0.357726
std        0.760363      1.219127      0.477608     0.674557     0.106917
min        0.000000      0.000000      0.000000     0.000000     0.000000
25%        1.637825      0.000000      0.000000     0.536273     0.303785
50%        2.182081      1.386294      0.000000     0.905054     0.370512
75%        2.616517      2.197225      0.693147     1.420111     0.435625
max        4.306728      5.525453      2.302585     4.408529     0.610260

# Verificación media / mediana

Podemos ver que los datos se normalizaron en gran medida

In [15]:
variables = ["l_Dt_del10mi", "l_Mtasa_mig1", "l_densidad_2", "l_tasa_ata1", "l_DRRIAlt", "indice"]

description = df[variables].describe()

# Calcula la mediana y crea un DataFrame para la fila de la mediana
median_row = pd.DataFrame(df[variables].median(), columns=['median']).transpose()

# Concatena el DataFrame de la mediana con la descripción
description_with_median = pd.concat([description, median_row])

print(description_with_median)

        l_Dt_del10mi  l_Mtasa_mig1  l_densidad_2  l_tasa_ata1    l_DRRIAlt  \
count    2457.000000   2465.000000   2465.000000  1557.000000  2456.000000
mean        2.124137      1.355510      0.426095     1.036280     0.357726
std         0.760363      1.219127      0.477608     0.674557     0.106917
min         0.000000      0.000000      0.000000     0.000000     0.000000
25%         1.637825      0.000000      0.000000     0.536273     0.303785
50%         2.182081      1.386294      0.000000     0.905054     0.370512
75%         2.616517      2.197225      0.693147     1.420111     0.435625
max         4.306728      5.525453      2.302585     4.408529     0.610260
median      2.182081      1.386294      0.000000     0.905054     0.370512

             indice
count   1552.000000
mean       1.216522
std        0.383593
min        0.247618
25%        0.953078
50%        1.187778
75%        1.456876
max        2.634011
median     1.187778

# Creando el índice

In [13]:
import numpy as np
import pandas as pd

#DataFrame llamado df con las variables y los campos logaritmizados

# Calcula el valor del índice para cada registro
df["indice"] = (df["l_Dt_del10mi"] + df["l_Mtasa_mig1"] + df["l_densidad_2"] + df["l_tasa_ata1"] + df["l_DRRIAlt"]) / 5

# Muestra el DataFrame con el nuevo campo "indice"
print(df)

      CVEGEO  CVE_ENT  CVE_MUN          Estado             Municipios  \
0       1001        1        1  Aguascalientes         Aguascalientes
1       1002        1        2  Aguascalientes               Asientos
2       1003        1        3  Aguascalientes               Calvillo
3       1004        1        4  Aguascalientes                  Cosío
4       1005        1        5  Aguascalientes            Jesús María
...      ...      ...      ...             ...                    ...
2460   32054       32       54       Zacatecas          Villa Hidalgo
2461   32055       32       55       Zacatecas             Villanueva
2462   32056       32       56       Zacatecas              Zacatecas
2463   32057       32       57       Zacatecas               Trancoso
2464   32058       32       58       Zacatecas  Santa María de la Paz

      DCVEGEO         DEstado             DMunicipio               DNOM_MUN  \
0         NaN  Aguascalientes         Aguascalientes         Aguascalientes
1         NaN  Aguascalientes               Asientos               Asientos
2         NaN  Aguascalientes               Calvillo               Calvillo
3         NaN  Aguascalientes                  Cosío                  Cosío
4         NaN  Aguascalientes            Jesús María            Jesús María
...       ...             ...                    ...                    ...
2460      NaN       Zacatecas          Villa Hidalgo          Villa Hidalgo
2461      NaN       Zacatecas             Villanueva             Villanueva
2462      NaN       Zacatecas              Zacatecas              Zacatecas
2463      NaN       Zacatecas               Trancoso               Trancoso
2464      NaN       Zacatecas  Santa María de la Paz  Santa María de la Paz

       DRRIAlt  ...  Mporcien_I  densidad_o             densidad_1  \
0     0.099400  ...         1.0         NaN         Aguascalientes
1     0.407417  ...         1.0         NaN               Asientos
2     0.419558  ...         0.0         NaN               Calvillo
3     0.446193  ...         0.0         NaN                  Cosío
4     0.265166  ...         2.0         NaN            Jesús María
...        ...  ...         ...         ...                    ...
2460  0.522400  ...         0.0         NaN          Villa Hidalgo
2461  0.482641  ...         1.0         NaN             Villanueva
2462  0.129917  ...         2.0         NaN              Zacatecas
2463  0.346497  ...         2.0         NaN               Trancoso
2464  0.609889  ...         0.0         NaN  Santa María de la Paz

      densidad_2  l_Dt_del10mi  l_Mtasa_mig1  l_densidad_2  l_tasa_ata1  \
0              2      3.640439      1.609438      1.098612     0.272353
1              1      3.100656      1.386294      0.693147     0.334943
2              1      2.986837      0.000000      0.693147     0.289028
3              2      2.844269      0.693147      1.098612     0.643356
4              2      3.211325      2.079442      1.098612     0.387738
...          ...           ...           ...           ...          ...
2460           1      1.719222      1.098612      0.693147     0.153666
2461           2      2.672378      1.386294      1.098612     0.905353
2462           1      3.465194      3.401197      0.693147     1.838397
2463           1      3.060649      1.609438      0.693147     1.635751
2464           0      2.655779      0.000000      0.000000     1.507939

      l_DRRIAlt    indice
0      0.094764  1.343121
1      0.341756  1.171359
2      0.350346  0.863872
3      0.368935  1.129664
4      0.235203  1.402464
...         ...       ...
2460   0.420288  0.816987
2461   0.393825  1.291292
2462   0.122145  1.904016
2463   0.297506  1.459298
2464   0.476165  0.927977

[2465 rows x 62 columns]

## guardamos en un nuevo archivo csv

In [14]:
new_csv_filename = "/home/omnibus/Documents/QGISS_Cartografia/Proyectos/criminal_mx/indice_psd/indice.csv"
df.to_csv(new_csv_filename, index=False)  # El parámetro index=False evita guardar el índice como columna

print(f"DataFrame con el nuevo campo 'indice' guardado en {new_csv_filename}")

DataFrame con el nuevo campo 'indice' guardado en /home/omnibus/Documents/QGISS_Cartografia/Proyectos/criminal_mx/indice_psd/indice.csv

In [ ]:
# Creamos otra vez el índice pero a partir de los datos sin normalizar

In [17]:
import numpy as np
import pandas as pd

# Supongamos que tienes un DataFrame llamado df con las variables y los campos logaritmizados

# Calcula el valor del índice para cada registro
df["indice2"] = (df["Dt_del10mi"] + df["Mtasa_mig1"] + df["densidad_2"] + df["tasa_ata1"] + df["DRRIAlt"]) / 5

# Muestra el DataFrame con el nuevo campo "indice2"
print(df)

      CVEGEO  CVE_ENT  CVE_MUN          Estado             Municipios  \
0       1001        1        1  Aguascalientes         Aguascalientes
1       1002        1        2  Aguascalientes               Asientos
2       1003        1        3  Aguascalientes               Calvillo
3       1004        1        4  Aguascalientes                  Cosío
4       1005        1        5  Aguascalientes            Jesús María
...      ...      ...      ...             ...                    ...
2460   32054       32       54       Zacatecas          Villa Hidalgo
2461   32055       32       55       Zacatecas             Villanueva
2462   32056       32       56       Zacatecas              Zacatecas
2463   32057       32       57       Zacatecas               Trancoso
2464   32058       32       58       Zacatecas  Santa María de la Paz

      DCVEGEO         DEstado             DMunicipio               DNOM_MUN  \
0         NaN  Aguascalientes         Aguascalientes         Aguascalientes
1         NaN  Aguascalientes               Asientos               Asientos
2         NaN  Aguascalientes               Calvillo               Calvillo
3         NaN  Aguascalientes                  Cosío                  Cosío
4         NaN  Aguascalientes            Jesús María            Jesús María
...       ...             ...                    ...                    ...
2460      NaN       Zacatecas          Villa Hidalgo          Villa Hidalgo
2461      NaN       Zacatecas             Villanueva             Villanueva
2462      NaN       Zacatecas              Zacatecas              Zacatecas
2463      NaN       Zacatecas               Trancoso               Trancoso
2464      NaN       Zacatecas  Santa María de la Paz  Santa María de la Paz

       DRRIAlt  ...  MOTRA  MNO_ESP  Mtasa_mig1  Mtasa_mi_1  Mpobtotal2  \
0     0.099400  ...   3239      101         4.0        43.0      961977
1     0.407417  ...     84        6         3.0        39.0       50864
2     0.419558  ...     60       11         0.0         9.0       60760
3     0.446193  ...     44        1         1.0        17.0       16918
4     0.265166  ...    581       21         7.0        73.0      130184
...        ...  ...    ...      ...         ...         ...         ...
2460  0.522400  ...     34        0         2.0        29.0       20177
2461  0.482641  ...     48        4         3.0        34.0       31804
2462  0.129917  ...   1774       75        29.0       294.0      155533
2463  0.346497  ...     39        0         4.0        49.0       20285
2464  0.609889  ...      5        0         0.0         0.0        2855

      Mporcien_I  densidad_o             densidad_1  densidad_2    indice2
0            1.0         NaN         Aguascalientes           2   8.704204
1            1.0         NaN               Asientos           1   5.203559
2            0.0         NaN               Calvillo           1   4.115513
3            0.0         NaN                  Cosío           2   4.107608
4            2.0         NaN            Jesús María           2   6.710150
...          ...         ...                    ...         ...        ...
2460         0.0         NaN          Villa Hidalgo           1   1.653737
2461         1.0         NaN             Villanueva           2   4.085958
2462         2.0         NaN              Zacatecas           1  13.279807
2463         2.0         NaN               Trancoso           1   5.964243
2464         0.0         NaN  Santa María de la Paz           0   3.472674

[2465 rows x 57 columns]

In [18]:
new_csv_filename = "/home/omnibus/Documents/QGISS_Cartografia/Proyectos/criminal_mx/indice_psd/indice_2_sin_transformar.csv"
df.to_csv(new_csv_filename, index=False)  # El parámetro index=False evita guardar el índice como columna

print(f"DataFrame con el nuevo campo 'indice' guardado en {new_csv_filename}")

DataFrame con el nuevo campo 'indice' guardado en /home/omnibus/Documents/QGISS_Cartografia/Proyectos/criminal_mx/indice_psd/indice_2_sin_transformar.csv

In [ ]:
# Ahora vamos a intentar también sacar el índice a partir de los datos normalizados

In [19]:
import pandas as pd
import numpy as np

df = pd.read_csv("/home/omnibus/Documents/QGISS_Cartografia/Proyectos/criminal_mx/indice_psd/cruce_normalizado_simple.csv")

# Supongamos que tienes un DataFrame llamado df con las variables y los campos logaritmizados

# Calcula el valor del índice para cada registro
df["indice_norm"] = (df["Dt_del10mi"] + df["Mtasa_mig1"] + df["densidad_2"] + df["tasa_ata1"] + df["DRRIAlt"]) / 5

# Muestra el DataFrame con el nuevo campo "indice2"
print(df)

      CVEGEO  CVE_ENT  CVE_MUN          Estado             Municipios  \
0       1001        1        1  Aguascalientes         Aguascalientes
1       1002        1        2  Aguascalientes               Asientos
2       1003        1        3  Aguascalientes               Calvillo
3       1004        1        4  Aguascalientes                  Cosío
4       1005        1        5  Aguascalientes            Jesús María
...      ...      ...      ...             ...                    ...
2460   32054       32       54       Zacatecas          Villa Hidalgo
2461   32055       32       55       Zacatecas             Villanueva
2462   32056       32       56       Zacatecas              Zacatecas
2463   32057       32       57       Zacatecas               Trancoso
2464   32058       32       58       Zacatecas  Santa María de la Paz

      DCVEGEO         DEstado             DMunicipio               DNOM_MUN  \
0         NaN  Aguascalientes         Aguascalientes         Aguascalientes
1         NaN  Aguascalientes               Asientos               Asientos
2         NaN  Aguascalientes               Calvillo               Calvillo
3         NaN  Aguascalientes                  Cosío                  Cosío
4         NaN  Aguascalientes            Jesús María            Jesús María
...       ...             ...                    ...                    ...
2460      NaN       Zacatecas          Villa Hidalgo          Villa Hidalgo
2461      NaN       Zacatecas             Villanueva             Villanueva
2462      NaN       Zacatecas              Zacatecas              Zacatecas
2463      NaN       Zacatecas               Trancoso               Trancoso
2464      NaN       Zacatecas  Santa María de la Paz  Santa María de la Paz

       DRRIAlt  ...  MOTRA  MNO_ESP  Mtasa_mig1  Mtasa_mi_1  Mpobtotal2  \
0     0.099400  ...   3239      101       0.016        43.0      961977
1     0.407417  ...     84        6       0.012        39.0       50864
2     0.419558  ...     60       11       0.000         9.0       60760
3     0.446193  ...     44        1       0.004        17.0       16918
4     0.265166  ...    581       21       0.028        73.0      130184
...        ...  ...    ...      ...         ...         ...         ...
2460  0.522400  ...     34        0       0.008        29.0       20177
2461  0.482641  ...     48        4       0.012        34.0       31804
2462  0.129917  ...   1774       75       0.116       294.0      155533
2463  0.346497  ...     39        0       0.016        49.0       20285
2464  0.609889  ...      5        0       0.000         0.0        2855

      Mporcien_I  densidad_o             densidad_1  densidad_2  indice_norm
0            1.0         NaN         Aguascalientes    0.222222     0.169689
1            1.0         NaN               Asientos    0.111111     0.165046
2            0.0         NaN               Calvillo    0.111111     0.158390
3            0.0         NaN                  Cosío    0.222222     0.180942
4            2.0         NaN            Jesús María    0.222222     0.169307
...          ...         ...                    ...         ...          ...
2460         0.0         NaN          Villa Hidalgo    0.111111     0.141226
2461         1.0         NaN             Villanueva    0.222222     0.183819
2462         2.0         NaN              Zacatecas    0.111111     0.169090
2463         2.0         NaN               Trancoso    0.111111     0.160488
2464         0.0         NaN  Santa María de la Paz    0.000000     0.166812

[2465 rows x 57 columns]

In [20]:
new_csv_filename = "/home/omnibus/Documents/QGISS_Cartografia/Proyectos/criminal_mx/indice_psd/indice_normalizado.csv"
df.to_csv(new_csv_filename, index=False)  # El parámetro index=False evita guardar el índice como columna

print(f"DataFrame con el nuevo campo 'indice' guardado en {new_csv_filename}")

DataFrame con el nuevo campo 'indice' guardado en /home/omnibus/Documents/QGISS_Cartografia/Proyectos/criminal_mx/indice_psd/indice_normalizado.csv